clone_depth: 5
version: "{branch}.{build}"

image:
  - Visual Studio 2019

environment:
  matrix:
    - GETH_ARCH: amd64
      GETH_CC: C:\msys64\mingw64\bin\gcc.exe
      PATH: C:\msys64\mingw64\bin;C:\Program Files (x86)\NSIS\;%PATH%

install:
  - git submodule update --init --depth 1 --recursive
  - go version

build_script:
  - ps: $env:VERSION = "$(git describe --always)"
  - go run build\ci.go install -dlgo -arch %GETH_ARCH% -cc %GETH_CC%
  - 7z a core-geth-win64-%VERSION%.zip .\build\bin\geth.exe
  - ps: Get-FileHash core-geth-win64-$env:VERSION.zip -Algorithm SHA256
  - ps: Get-FileHash core-geth-win64-$env:VERSION.zip -Algorithm SHA256 | Out-File core-geth-win64-$env:VERSION.zip.sha256
  - 7z a core-geth-alltools-win64-%VERSION%.zip .\build\bin\*
  - ps: Get-FileHash core-geth-alltools-win64-$env:VERSION.zip -Algorithm SHA256
  - ps: Get-FileHash core-geth-alltools-win64-$env:VERSION.zip | Out-File core-geth-alltools-win64-$env:VERSION.zip.sha256

for:
  - branches:
      only:
        - /v\d*\.\d*\.\d*.*/
    artifacts:
      - path: '*core-geth-win64*.zip'
        name: geth
      - path: '*core-geth-win64*.zip.sha256'
        name: geth-sha256
      - path: '*core-geth-alltools*.zip'
        name: alltools
      - path: '*core-geth-alltools*.zip.sha256'
        name: alltools-sha256

deploy:
  provider: GitHub
  repository: etclabscore/core-geth
  artifact: /core-geth.*-win64-.*\.zip.*/
  auth_token:
    secure: tLl/Lbjrer4HCRxAUD/KHocjIsyRWuR7QeK5OCMVTv5lCF2IUKCT6h51nNW4hjOZ
  draft: true
  on:
    appveyor_repo_tag: true
