name: EVMC

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-evmc:
    name: EVMC/EVM+EWASM State Tests
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install cmake
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install -y cmake
          cmake --version

      - name: Install necessary GLIBCXX version
        run: |
          strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update -y
          sudo apt-get install -y gcc-9 g++-9
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 90
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90
          g++ --version
          gcc --version
          strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          git config --global --add safe.directory $(pwd)/tests/evm-benchmarks
          git config --global --add safe.directory $(pwd)/tests/testdata
          git config --global --add safe.directory $(pwd)/tests/testdata/LegacyTests
          git submodule update --init --recursive
          export GOBIN=${HOME}/go/bin
          mkdir -p "${GOBIN}"
          export PATH="${PATH}:${GOBIN}"
          go install -x golang.org/x/mobile/cmd/gomobile@latest
          gomobile init

      - name: Test EVMC
        run: |
          make test-evmc
